server.port=9084
spring.application.name=warehouse-service-twin

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-round-frost-a10slzy6-pooler.ap-southeast-1.aws.neon.tech/warehouse_db?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:warehouse_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:warehouse_admin(123)}
spring.datasource.driver-class-name=org.postgresql.Driver

# Service URLs
INVENTORY_SERVICE_URL=${INVENTORY_SERVICE_URL:http://localhost:8082}

# JPA Configuration
# Set to 'none' so Hibernate does not try to recreate or modify existing tables initialized by Go
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
