apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smart-order

resources:
  - namespace.yaml
  - all-services.yaml
  - ingress.yaml

secretGenerator:
  - name: smart-order-secrets
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true
