global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'inventory-java:8082'
          - 'order-java:8083'
          - 'warehouse-java-twin:9084'

  - job_name: 'go-services'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'inventory-go-twin:9082'
          - 'order-go-twin:9083'
          - 'warehouse-go:8084'
