spring.application.name=warehouse-twin
server.port=9084

# --- Database Configuration (Neon) ---
spring.datasource.url=jdbc:postgresql://ep-round-frost-a10slzy6-pooler.ap-southeast-1.aws.neon.tech:5432/warehouse_db?sslmode=require
spring.datasource.username=warehouse_admin
spring.datasource.password=warehouse_admin(123)
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

INVENTORY_SERVICE_URL=${INVENTORY_SERVICE_URL:http://localhost:8082}

# --- Observability ---
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always