vault_jwt_secret: "dummy"
vault_internal_service_token: "dummy"
vault_auth_db_url: "dummy"
vault_order_db_url: "dummy"
vault_inventory_db_url: "dummy"
vault_warehouse_db_url: "dummy"
vault_delivery_db_url: "dummy"
vault_notification_db_url: "dummy"
vault_smtp_email: "dummy"
vault_smtp_password: "dummy"
