{
 "title": "Smart Order Observability",
 "tags": [
  "kubernetes",
  "lpg",
  "plg"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Core Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"smart-order\", pod!=\"\", container!=\"POD\", container!=\"\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"smart-order\", pod!=\"\", container!=\"POD\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error Log Rate per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (container) (rate({namespace=\"smart-order\"} |= \"ERROR\" [1m]))",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}